type Customer {
  username: String @unique
  password: String
  email: String!
  isEmailVerified: Boolean
  address: [Address!] @relation
  order: [Order!] @relation
}

type Address {
  customer: Customer!
  province: String!
  city: String!
  street: String!
  telephone: String!
}

type Product {
  name: String!
  description: String
  price: Float
  quantity: Int
}

type OrderedProduct {
  product: Product
  quantity: Int
  price: Float
}

type Order {
  orderNumber: String @unique
  customer: Customer!
  shipAddress: Address!
  status: String
  creationDate: Time
  shipDate: Time
  products: [OrderedProduct!]! @relation
}
